version: '3.8'

services:
  local-dns:
    build:
      context: .
    image: aperture:local-dns
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    network_mode: host